rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0

script: bundle exec rake spec

gemfile:
  - Gemfile
  - gemfiles/gemfile.chef10

matrix:
  allow_failures:
    - rvm: 1.8.7           # We support 1.8.7, but chef-pedant doesn't
    - rvm: jruby-19mode    # Mixlib Shellout uses fork+exec
